%% ========================================================================
%% COMPLETE MATLAB STEREO CALIBRATION + OPENCV EXPORT
%% ========================================================================
%%
%% This script combines:
%% 1. MATLAB auto-generated stereo calibration code
%% 2. OpenCV export with rectifyStereoImages Q matrix
%%
%% Author: Alessandro (Unlook Project) + MATLAB auto-generated code
%% Date: 2025-11-17
%% ========================================================================

%% ========================================================================
%% PART 1: STEREO CALIBRATION (Auto-generated by MATLAB)
%% ========================================================================

fprintf('==================================================\n');
fprintf('PART 1: STEREO CALIBRATION\n');
fprintf('==================================================\n\n');

% Define images to process
imageFileNames1 = {'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_000.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_001.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_002.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_003.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_004.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_005.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_006.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_007.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_008.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_009.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_010.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_011.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_012.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_013.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_014.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_015.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_016.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_017.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_018.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_019.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_020.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_021.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_022.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_023.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_024.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_025.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_026.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_027.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_028.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_029.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_030.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_031.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_032.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\right\frame_033.png',...
    };
imageFileNames2 = {'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_000.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_001.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_002.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_003.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_004.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_005.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_006.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_007.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_008.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_009.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_010.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_011.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_012.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_013.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_014.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_015.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_016.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_017.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_018.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_019.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_020.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_021.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_022.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_023.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_024.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_025.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_026.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_027.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_028.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_029.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_030.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_031.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_032.png',...
    'C:\Users\Alessandro\Downloads\dataset_20251115_191610\left\frame_033.png',...
    };

fprintf('Detecting checkerboard patterns in %d image pairs...\n', length(imageFileNames1));

% Detect calibration pattern in images
detector = vision.calibration.stereo.CheckerboardDetector();
minCornerMetric = 0.120000;
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames1, imageFileNames2, 'MinCornerMetric', minCornerMetric, 'HighDistortion', true);

fprintf('✅ Pattern detection complete. Images used: %d\n', sum(imagesUsed));

% Generate world coordinates for the planar pattern keypoints
squareSize = 24.000000;  % in millimeters
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

fprintf('Running stereo calibration...\n');

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

fprintf('✅ Calibration complete!\n\n');

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);
title('Reprojection Errors');

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');
title('Camera Extrinsics');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

fprintf('\nCalibration quality:\n');
fprintf('  Mean reprojection error: %.4f pixels\n', stereoParams.MeanReprojectionError);
fprintf('  Baseline: %.4f mm\n', norm(stereoParams.TranslationOfCamera2));
fprintf('\n');

%% ========================================================================
%% PART 2: EXPORT TO OPENCV FORMAT
%% ========================================================================

fprintf('==================================================\n');
fprintf('PART 2: EXPORT TO OPENCV FORMAT\n');
fprintf('==================================================\n\n');

% Extract parameters DIRECTLY from stereoParams object (R2025b compatible!)
fprintf('Extracting calibration parameters directly from stereoParams...\n');

% Camera 1 intrinsics
cameraMatrix1 = stereoParams.CameraParameters1.K';  % MATLAB stores as transpose
distortionCoefficients1 = [stereoParams.CameraParameters1.RadialDistortion(1:2), ...
                           stereoParams.CameraParameters1.TangentialDistortion, ...
                           stereoParams.CameraParameters1.RadialDistortion(3)];

% Camera 2 intrinsics
cameraMatrix2 = stereoParams.CameraParameters2.K';  % MATLAB stores as transpose
distortionCoefficients2 = [stereoParams.CameraParameters2.RadialDistortion(1:2), ...
                           stereoParams.CameraParameters2.TangentialDistortion, ...
                           stereoParams.CameraParameters2.RadialDistortion(3)];

% Stereo extrinsics
rotationOfCamera2 = stereoParams.RotationOfCamera2;
translationOfCamera2 = stereoParams.TranslationOfCamera2;

% Image size
imageSize = fliplr(stereoParams.CameraParameters1.ImageSize);  % [height, width] → [width, height]

fprintf('✅ Parameters extracted directly from stereoParams object\n');
fprintf('   Image size: %dx%d\n', imageSize(1), imageSize(2));
fprintf('   Baseline: %.6f mm\n', norm(translationOfCamera2));
fprintf('\n');

% Rectify images to get Q matrix
fprintf('Computing rectification matrices...\n');
I2 = imread(imageFileNames2{1});
[J1, J2, reprojectionMatrix, camMatrix1Rect, camMatrix2Rect, R1, R2] = ...
    rectifyStereoImages(I1, I2, stereoParams, 'OutputView', 'full');

fprintf('✅ Rectification complete!\n\n');

% Display Q matrix
fprintf('REPROJECTION MATRIX (Q) from MATLAB rectifyStereoImages:\n');
disp(reprojectionMatrix);
fprintf('\n');

%% ========================================================================
%% PART 3: WRITE OPENCV YAML FILE
%% ========================================================================

fprintf('==================================================\n');
fprintf('PART 3: WRITING OPENCV YAML FILE\n');
fprintf('==================================================\n\n');

outputFile = 'C:\Users\Alessandro\Downloads\calib-matlab-complete-export.yaml';
fid = fopen(outputFile, 'w');

% Write YAML header
fprintf(fid, '%%YAML:1.0\n');
fprintf(fid, '---\n');
fprintf(fid, 'calibration_date: "%s"\n', datestr(now, 'yyyy-mm-ddTHH:MM:SS'));
fprintf(fid, 'calibration_method: "MATLAB_rectifyStereoImages_COMPLETE_EXPORT"\n');
fprintf(fid, 'note: "Exported with official MATLAB stereoParametersToOpenCV + rectifyStereoImages"\n');
fprintf(fid, 'dataset_path: "dataset_20251115_191610"\n');
fprintf(fid, 'pattern_type: "checkerboard"\n');
fprintf(fid, 'square_size_mm: %.1f\n', squareSize);
fprintf(fid, 'num_image_pairs: %d\n', length(imageFileNames1));
fprintf(fid, 'valid_image_pairs: %d\n', sum(imagesUsed));
fprintf(fid, '\n');

% Image size
fprintf(fid, 'image_width: %d\n', imageSize(1));  % imageSize = [width, height] after fliplr
fprintf(fid, 'image_height: %d\n', imageSize(2));
fprintf(fid, '\n');

% Camera matrix left (K1) - Already in OpenCV format!
fprintf(fid, 'camera_matrix_left: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 3\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
for i = 1:numel(cameraMatrix1)
    fprintf(fid, '%.16e', cameraMatrix1(i));
    if i < numel(cameraMatrix1), fprintf(fid, ', '); end
    if mod(i, 3) == 0 && i < numel(cameraMatrix1), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Distortion coefficients left (D1)
fprintf(fid, 'distortion_coeffs_left: !!opencv-matrix\n');
fprintf(fid, '   rows: %d\n', length(distortionCoefficients1));
fprintf(fid, '   cols: 1\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
for i = 1:length(distortionCoefficients1)
    fprintf(fid, '%.16e', distortionCoefficients1(i));
    if i < length(distortionCoefficients1), fprintf(fid, ', '); end
end
fprintf(fid, ' ]\n\n');

% Camera matrix right (K2) - Already in OpenCV format!
fprintf(fid, 'camera_matrix_right: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 3\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
for i = 1:numel(cameraMatrix2)
    fprintf(fid, '%.16e', cameraMatrix2(i));
    if i < numel(cameraMatrix2), fprintf(fid, ', '); end
    if mod(i, 3) == 0 && i < numel(cameraMatrix2), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Distortion coefficients right (D2)
fprintf(fid, 'distortion_coeffs_right: !!opencv-matrix\n');
fprintf(fid, '   rows: %d\n', length(distortionCoefficients2));
fprintf(fid, '   cols: 1\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
for i = 1:length(distortionCoefficients2)
    fprintf(fid, '%.16e', distortionCoefficients2(i));
    if i < length(distortionCoefficients2), fprintf(fid, ', '); end
end
fprintf(fid, ' ]\n\n');

% Rotation matrix (R) - TRANSPOSE!
fprintf(fid, 'rotation_matrix: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 3\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
R_transposed = rotationOfCamera2';
for i = 1:numel(R_transposed)
    fprintf(fid, '%.16e', R_transposed(i));
    if i < numel(R_transposed), fprintf(fid, ', '); end
    if mod(i, 3) == 0 && i < numel(R_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Translation vector (T) - in MILLIMETERS!
fprintf(fid, 'translation_vector: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 1\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
for i = 1:length(translationOfCamera2)
    fprintf(fid, '%.16e', translationOfCamera2(i));
    if i < length(translationOfCamera2), fprintf(fid, ', '); end
end
fprintf(fid, ' ]\n\n');

% Baseline
baseline_mm = norm(translationOfCamera2);
fprintf(fid, 'baseline_mm: %.16e\n\n', baseline_mm);

% Rectification transform left (R1) - TRANSPOSE!
fprintf(fid, 'rectification_transform_left: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 3\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
R1_transposed = R1';
for i = 1:numel(R1_transposed)
    fprintf(fid, '%.16e', R1_transposed(i));
    if i < numel(R1_transposed), fprintf(fid, ', '); end
    if mod(i, 3) == 0 && i < numel(R1_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Rectification transform right (R2) - TRANSPOSE!
fprintf(fid, 'rectification_transform_right: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 3\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
R2_transposed = R2';
for i = 1:numel(R2_transposed)
    fprintf(fid, '%.16e', R2_transposed(i));
    if i < numel(R2_transposed), fprintf(fid, ', '); end
    if mod(i, 3) == 0 && i < numel(R2_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Projection matrix left (P1) - TRANSPOSE!
fprintf(fid, 'projection_matrix_left: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 4\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
P1_transposed = camMatrix1Rect';
for i = 1:numel(P1_transposed)
    fprintf(fid, '%.16e', P1_transposed(i));
    if i < numel(P1_transposed), fprintf(fid, ', '); end
    if mod(i, 4) == 0 && i < numel(P1_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Projection matrix right (P2) - TRANSPOSE!
fprintf(fid, 'projection_matrix_right: !!opencv-matrix\n');
fprintf(fid, '   rows: 3\n');
fprintf(fid, '   cols: 4\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
P2_transposed = camMatrix2Rect';
for i = 1:numel(P2_transposed)
    fprintf(fid, '%.16e', P2_transposed(i));
    if i < numel(P2_transposed), fprintf(fid, ', '); end
    if mod(i, 4) == 0 && i < numel(P2_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% CRITICAL: Disparity-to-depth matrix (Q) - TRANSPOSE!
fprintf(fid, 'disparity_to_depth_matrix: !!opencv-matrix\n');
fprintf(fid, '   rows: 4\n');
fprintf(fid, '   cols: 4\n');
fprintf(fid, '   dt: d\n');
fprintf(fid, '   data: [ ');
Q_transposed = reprojectionMatrix';
for i = 1:numel(Q_transposed)
    fprintf(fid, '%.16e', Q_transposed(i));
    if i < numel(Q_transposed), fprintf(fid, ', '); end
    if mod(i, 4) == 0 && i < numel(Q_transposed), fprintf(fid, '\n       '); end
end
fprintf(fid, ' ]\n\n');

% Quality metrics
fprintf(fid, 'rms_reprojection_error: %.16e\n', stereoParams.MeanReprojectionError);
fprintf(fid, 'opencv_version: "4.6.0"\n');

fclose(fid);

fprintf('✅ Calibration exported to: %s\n\n', outputFile);

%% ========================================================================
%% FINAL SUMMARY
%% ========================================================================

fprintf('==================================================\n');
fprintf('EXPORT SUMMARY\n');
fprintf('==================================================\n\n');
fprintf('Output file: %s\n\n', outputFile);
fprintf('Calibration quality:\n');
fprintf('  Image pairs used: %d / %d\n', sum(imagesUsed), length(imageFileNames1));
fprintf('  Mean reprojection error: %.4f pixels\n', stereoParams.MeanReprojectionError);
fprintf('  Baseline: %.4f mm\n', baseline_mm);
fprintf('\n');
fprintf('Q Matrix (reprojectionMatrix) from MATLAB:\n');
fprintf('  Q(1,4) = -cx = %.4f\n', reprojectionMatrix(1,4));
fprintf('  Q(2,4) = -cy = %.4f\n', reprojectionMatrix(2,4));
fprintf('  Q(3,4) = f   = %.4f\n', reprojectionMatrix(3,4));
fprintf('  Q(4,3) = -1/baseline = %.8f\n', reprojectionMatrix(4,3));
fprintf('  Baseline from Q: %.4f mm\n', -1/reprojectionMatrix(4,3));
fprintf('\n');
fprintf('⚠️  IMPORTANT:\n');
fprintf('1. All matrices converted to OpenCV row-major format\n');
fprintf('2. Translation vector in MILLIMETERS\n');
fprintf('3. Q matrix from MATLAB rectifyStereoImages (not OpenCV stereoRectify)\n');
fprintf('4. Image size: %dx%d (width x height)\n', imageSize(1), imageSize(2));
fprintf('\n');
fprintf('Next steps:\n');
fprintf('1. Copy YAML file to Raspberry Pi: /unlook_calib/\n');
fprintf('2. ln -sf calib-matlab-complete-export.yaml /unlook_calib/default.yaml\n');
fprintf('3. Test scan with: unlook\n');
fprintf('\n');
fprintf('==================================================\n');

% Save stereoParams for future use
save('C:\Users\Alessandro\Downloads\stereoParams.mat', 'stereoParams');
fprintf('✅ stereoParams saved to: stereoParams.mat\n');
