# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_APP_VALUE_LEN "1")
set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/alessandro/unlook-standalone;/home/alessandro/unlook-standalone/build_test")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Development;Runtime;Unspecified")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_APPLICATIONS_DESCRIPTION "Main GUI application and command-line tools")
set(CPACK_COMPONENT_APPLICATIONS_DISABLED "FALSE")
set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Unlook Scanner Applications")
set(CPACK_COMPONENT_APPLICATIONS_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_APPLICATIONS_HIDDEN "FALSE")
set(CPACK_COMPONENT_APPLICATIONS_REQUIRED "TRUE")
set(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "Headers and development tools for API integration")
set(CPACK_COMPONENT_DEVELOPMENT_DISABLED "FALSE")
set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development Files")
set(CPACK_COMPONENT_DEVELOPMENT_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_DEVELOPMENT_HIDDEN "FALSE")
set(CPACK_COMPONENT_DEVELOPMENT_REQUIRED "FALSE")
set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "API documentation and user guides")
set(CPACK_COMPONENT_DOCUMENTATION_DISABLED "FALSE")
set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
set(CPACK_COMPONENT_DOCUMENTATION_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_DOCUMENTATION_HIDDEN "FALSE")
set(CPACK_COMPONENT_DOCUMENTATION_REQUIRED "FALSE")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Example applications and validation tests")
set(CPACK_COMPONENT_EXAMPLES_DISABLED "FALSE")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Examples and Tests")
set(CPACK_COMPONENT_EXAMPLES_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_EXAMPLES_HIDDEN "FALSE")
set(CPACK_COMPONENT_EXAMPLES_REQUIRED "FALSE")
set(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "Shared libraries and API headers")
set(CPACK_COMPONENT_LIBRARIES_DISABLED "FALSE")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Unlook Scanner Libraries")
set(CPACK_COMPONENT_LIBRARIES_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_LIBRARIES_HIDDEN "FALSE")
set(CPACK_COMPONENT_LIBRARIES_REQUIRED "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libopencv-dev (>= 4.0), qtbase5-dev (>= 5.12), libqt5widgets5, build-essential, cmake")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alessandro Cursoli <alessandro.cursoli@supernovaindustries.com>")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "graphics")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "libopencv-contrib-dev")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "UnlookScanner built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "DEB;TGZ;RPM")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/home/alessandro/unlook-standalone;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/alessandro/unlook-standalone/cmake")
set(CPACK_NSIS_DISPLAY_NAME "unlook-scanner")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "unlook-scanner")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/alessandro/unlook-standalone/build_test/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "alessandro.cursoli@supernovaindustries.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Industrial-grade 3D scanner with 0.005mm precision for quality control, education, and research applications.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Unlook 3D Scanner - Professional Open Source 3D Scanner")
set(CPACK_PACKAGE_FILE_NAME "unlook-scanner-1.0.0-cm4-arm64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/SupernovaIndustries/unlook-standalone")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "unlook-scanner")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "unlook-scanner")
set(CPACK_PACKAGE_NAME "unlook-scanner")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Supernova Industries")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/alessandro/unlook-standalone/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/alessandro/unlook-standalone/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.25/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "aarch64")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Graphics")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_REQUIRES "opencv-devel >= 4.0, qt5-qtbase-devel >= 5.12")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/alessandro/unlook-standalone;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/alessandro/unlook-standalone/build_test/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "unlook-scanner-1.0.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/alessandro/unlook-standalone/build_test/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
